require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/pacient_cards", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # PacientCard. As you add validations to PacientCard, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PacientCard.create! valid_attributes
      get pacient_cards_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      pacient_card = PacientCard.create! valid_attributes
      get pacient_card_url(pacient_card)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_pacient_card_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      pacient_card = PacientCard.create! valid_attributes
      get edit_pacient_card_url(pacient_card)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PacientCard" do
        expect {
          post pacient_cards_url, params: { pacient_card: valid_attributes }
        }.to change(PacientCard, :count).by(1)
      end

      it "redirects to the created pacient_card" do
        post pacient_cards_url, params: { pacient_card: valid_attributes }
        expect(response).to redirect_to(pacient_card_url(PacientCard.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PacientCard" do
        expect {
          post pacient_cards_url, params: { pacient_card: invalid_attributes }
        }.to change(PacientCard, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post pacient_cards_url, params: { pacient_card: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested pacient_card" do
        pacient_card = PacientCard.create! valid_attributes
        patch pacient_card_url(pacient_card), params: { pacient_card: new_attributes }
        pacient_card.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the pacient_card" do
        pacient_card = PacientCard.create! valid_attributes
        patch pacient_card_url(pacient_card), params: { pacient_card: new_attributes }
        pacient_card.reload
        expect(response).to redirect_to(pacient_card_url(pacient_card))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        pacient_card = PacientCard.create! valid_attributes
        patch pacient_card_url(pacient_card), params: { pacient_card: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested pacient_card" do
      pacient_card = PacientCard.create! valid_attributes
      expect {
        delete pacient_card_url(pacient_card)
      }.to change(PacientCard, :count).by(-1)
    end

    it "redirects to the pacient_cards list" do
      pacient_card = PacientCard.create! valid_attributes
      delete pacient_card_url(pacient_card)
      expect(response).to redirect_to(pacient_cards_url)
    end
  end
end
