require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/specials", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Special. As you add validations to Special, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Special.create! valid_attributes
      get specials_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      special = Special.create! valid_attributes
      get special_url(special)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_special_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      special = Special.create! valid_attributes
      get edit_special_url(special)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Special" do
        expect {
          post specials_url, params: { special: valid_attributes }
        }.to change(Special, :count).by(1)
      end

      it "redirects to the created special" do
        post specials_url, params: { special: valid_attributes }
        expect(response).to redirect_to(special_url(Special.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Special" do
        expect {
          post specials_url, params: { special: invalid_attributes }
        }.to change(Special, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post specials_url, params: { special: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested special" do
        special = Special.create! valid_attributes
        patch special_url(special), params: { special: new_attributes }
        special.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the special" do
        special = Special.create! valid_attributes
        patch special_url(special), params: { special: new_attributes }
        special.reload
        expect(response).to redirect_to(special_url(special))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        special = Special.create! valid_attributes
        patch special_url(special), params: { special: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested special" do
      special = Special.create! valid_attributes
      expect {
        delete special_url(special)
      }.to change(Special, :count).by(-1)
    end

    it "redirects to the specials list" do
      special = Special.create! valid_attributes
      delete special_url(special)
      expect(response).to redirect_to(specials_url)
    end
  end
end
